# Generated by Django 5.2.8 on 2025-11-22 08:55

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0001_enable_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('brand_name', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('footwear', 'Footwear'), ('tops', 'Tops'), ('bottoms', 'Bottoms'), ('outerwear', 'Outerwear'), ('accessories', 'Accessories'), ('swimwear', 'Swimwear')], max_length=50)),
                ('image_url', models.URLField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('colors', models.JSONField(blank=True, default=list)),
                ('style_tags', models.JSONField(blank=True, default=list)),
                ('visual_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True)),
                ('text_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['product_id'],
                'indexes': [models.Index(fields=['category'], name='products_categor_fce6e6_idx'), models.Index(fields=['brand_name'], name='products_brand_n_a8dacd_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScrapedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=1000)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('source', models.CharField(choices=[('pinterest', 'Pinterest'), ('instagram', 'Instagram')], max_length=20)),
                ('caption', models.TextField(blank=True, null=True)),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('comments', models.IntegerField(blank=True, null=True)),
                ('posted_date', models.DateTimeField(blank=True, null=True)),
                ('user_info', models.JSONField(blank=True, default=dict)),
                ('query', models.CharField(blank=True, max_length=255)),
                ('visual_embedding', pgvector.django.vector.VectorField(blank=True, dimensions=512, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scraped_images',
                'ordering': ['-scraped_at'],
                'indexes': [models.Index(fields=['-scraped_at'], name='scraped_ima_scraped_43b00d_idx'), models.Index(fields=['source'], name='scraped_ima_source_ffdfc0_idx')],
            },
        ),
    ]
