# Generated by Django 5.2.8 on 2025-11-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pdp_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
